apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-product-app
  labels:  
    app: i27-product-app   
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-product-app
  template:
    metadata:
      labels:
        app: i27-product-app
    spec:
      containers:
      - name: i27-product-app
        image: DIT # this will be replaced by shared library
        ports:
        - containerPort: 8132
---
# Service 
apiVersion: v1
kind: Service           
metadata:
  name: i27-product-service
spec: 
  selector:
    app: i27-product-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8132
  type: NodePort